# Generated by Django 4.0.1 on 2022-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Null Person', max_length=100)),
                ('email', models.EmailField(default='null@null.null', max_length=254)),
                ('header', models.CharField(default='Null Header', max_length=100)),
                ('content', models.TextField(default='Null Content', max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
                ('dealt_with', models.BooleanField(default=False)),
            ],
        ),
    ]
