# Generated by Django 4.0.1 on 2022-02-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_alter_image_image'),
        ('portfolio', '0002_alter_work_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='description_is',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='description_en',
            field=models.TextField(default=' ', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='description_is',
            field=models.TextField(default=' na ', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ManyToManyField(to='media_app.Image'),
        ),
    ]
