# Generated by Django 4.0.1 on 2022-02-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_thumbnail'),
        ('portfolio', '0004_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_app.thumbnail'),
        ),
    ]
