# Generated by Django 4.0.1 on 2022-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_description_language_education_language_and_more'),
        ('portfolio', '0005_alter_work_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='skill',
            field=models.ManyToManyField(to='cv.Skill'),
        ),
    ]
