# Generated by Django 4.0.1 on 2022-02-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_work_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.group'),
        ),
    ]
