# Generated by Django 4.0.1 on 2022-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_work_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='subgroup',
            field=models.CharField(default='Misc', max_length=64),
        ),
    ]
