# Generated by Django 4.0.1 on 2022-02-12 13:01

from django.db import migrations, models
import media_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=media_app.models.get_def_name),
        ),
    ]
