# Generated by Django 4.0.1 on 2022-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='label',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AddField(
            model_name='bigsectionentry',
            name='label',
            field=models.CharField(default='N/A', max_length=64),
        ),
    ]
