# Generated by Django 4.0.1 on 2022-01-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_baseinfo_label_bigsectionentry_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinfo',
            old_name='name',
            new_name='text',
        ),
    ]
