# Generated by Django 4.0.1 on 2022-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_baseinfo_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigsectionentry',
            name='subheader',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='label',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
