# Generated by Django 4.0.1 on 2022-02-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_bigsectionentry_subheader_section_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=28)),
                ('category', models.CharField(max_length=28)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
