# Generated by Django 4.0.1 on 2022-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
