# Generated by Django 4.0.1 on 2022-02-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
                ('years', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='BigSectionEntry',
        ),
    ]
