# Generated by Django 4.0.1 on 2022-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_education_delete_bigsectionentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='years',
        ),
        migrations.AddField(
            model_name='education',
            name='end',
            field=models.CharField(default='/', max_length=128),
        ),
        migrations.AddField(
            model_name='education',
            name='start',
            field=models.CharField(default='/', max_length=128),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='/', max_length=128),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(default='/', max_length=128),
        ),
    ]
