# Generated by Django 4.0.1 on 2022-02-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default='description here. Lorem Ipsum sig dol loriet', max_length=1024),
        ),
    ]
