# Generated by Django 4.0.1 on 2022-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_alter_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=512)),
            ],
        ),
    ]
