# Generated by Django 4.0.1 on 2022-02-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=16)),
            ],
        ),
    ]
